### ISSUE TITLE
api-ai-ruby dependence 

### ISSUE THREAD

**Issue by luizcarvalho** [manicholls/lita-api-ai#2]
Hello my friend, one question.

Your gemspec, perhaps, should have` api-ai-ruby` as` runtime_dependency` ?

**Comment by manicholls** [comment]
I haven't had a chance to review today but you're probably right.  Feel free to submit a PR against this, otherwise I'll try to get to it this week.

**Comment by manicholls** [comment]
I believe this was fixed with your pull request - i just forgot to close this off.
